// packages/frontend/src/components/dialogs/FileInformationDialog.vue
<template>
	<Dialog @update:open="onOpen">
		<DialogTrigger v-if="hasDefaultSlot">
			<slot />
		</DialogTrigger>
		<DialogTrigger
			v-else
			class="h-full w-full absolute"
			as="a"
			:href="file?.url"
			target="_blank"
			rel="noopener noreferrer"
			variant="none"
			@click.left.stop="event => event.preventDefault()"
		/>
		<DialogContent
			class="max-w-[calc(100vw-8rem)] max-h-[calc(100vh-8rem)] min-h-[calc(100vh-8rem)]"
			:class="[isVerticalImage ? '!w-fit' : '!w-max']"
		>
			<div class="grid grid-cols-[1fr,400px] gap-4">
				<div
					class="w-full"
					:class="[isFileImage(file) || isFileVideo(file) ? 'h-[calc(100vh-11rem)]' : 'h-auto']"
				>
					<img
						v-if="isFileImage(file)"
						ref="fileElement"
						:src="file.url"
						class="h-full object-contain hidden md:block"
						@load="onImageLoad"
					/>
					<media-controller v-else-if="isFileVideo(file)" class="h-full hidden md:block">
						<!-- eslint-disable-next-line vue/no-deprecated-slot-attribute -->
						<video slot="media" :src="file.url" crossorigin="" class="h-full"></video>
						<media-control-bar>
							<media-play-button></media-play-button>
							<media-mute-button></media-mute-button>
							<media-volume-range></media-volume-range>
							<media-time-range></media-time-range>
							<media-pip-button></media-pip-button>
							<media-fullscreen-button></media-fullscreen-button>
						</media-control-bar>
					</media-controller>

					<media-controller v-else-if="isFileAudio(file)" audio class="hidden md:block">
						<!-- eslint-disable-next-line vue/no-deprecated-slot-attribute -->
						<audio slot="media" :src="file.url"></audio>
						<media-control-bar>
							<media-play-button></media-play-button>
							<media-time-display show-duration></media-time-display>
							<media-time-range></media-time-range>
							<media-playback-rate-button></media-playback-rate-button>
							<media-mute-button></media-mute-button>
							<media-volume-range></media-volume-range>
						</media-control-bar>
					</media-controller>

					<span v-else class="text-light-100 h-full items-center hidden md:flex"
						>Sorry but this file can't be previewed at this time.</span
					>
				</div>

				<!-- File information panel -->
				<div class="max-w-[400px] flex flex-col">
					<div class="max-h-[calc(100vh-12rem)">
						<ScrollArea class="inline-table">
							<div class="mb-8 max-w-[calc(100vw-12rem)]">
								<h2 class="text-light-100 mb-2">Actions</h2>
								<div class="flex justify-between gap-2 flex-wrap">
									<Button class="flex-1" @click="copyLink">{{
										isCopying ? 'Copied!' : 'Copy link'
									}}</Button>
									<Button
										as="a"
										:href="file.url"
										target="_blank"
										rel="noopener noreferrer"
										class="flex-1"
									>
										Open
									</Button>
									<ConfirmationDialog
										title="Delete file"
										message="The file will be deleted and gone forever with no way to recover it. It will also remove it from any albums that you added it to. Are you sure?"
										proceedText="Delete"
										:callback="doDeleteFile"
										><Button variant="destructive">Delete</Button></ConfirmationDialog
									>
									<div class="basis-full h-0"></div>
									<ConfirmationDialog
										v-if="isFileImage(file) || isFileVideo(file)"
										title="Regenerate thumbnail"
										message="If the file has a broken thumbnail this will try to fix that. Are you sure?"
										proceedText="Continue"
										:callback="doRegenerateThumbnail"
									>
										<Button>Regenerate thumbnail</Button></ConfirmationDialog
									>
									<Button as="a" :href="file.url" :download="file.original" class="flex-1">
										Download
									</Button>
									<ConfirmationDialog
										v-if="isAdmin && !file.quarantine"
										title="Quarantine file"
										message="The file will be quarantined and gone temporarily. Are you sure?"
										proceedText="Quarantine"
										:callback="doQuarantineFile"
									>
										<Button variant="destructive">Quarantine</Button></ConfirmationDialog
									>
									<ConfirmationDialog
										v-if="isAdmin && file.quarantine"
										title="Allow file"
										message="The file will be un-quarantined and be available again. Are you sure?"
										proceedText="Allow"
										:callback="doAllowFile"
										><Button variant="destructive">Allow</Button></ConfirmationDialog
									>
								</div>
							</div>

							<div class="mb-8 max-w-[calc(100vw-12rem)]">
								<h2 class="text-light-100">File info</h2>

								<InputWithOverlappingLabel :value="file.uuid" class="mt-4" label="UUID" readOnly />
								<InputWithOverlappingLabel :value="file.name" class="mt-4" label="Name" readOnly />
								<InputWithOverlappingLabel
									:value="file.original"
									class="mt-4"
									label="Original Name"
									readOnly
								/>
								<InputWithOverlappingLabel
									:value="file.ip"
									class="mt-4"
									label="IP"
									type="link"
									:href="`/dashboard/admin/ip/${file.ip}`"
									readOnly
								/>
								<InputWithOverlappingLabel
									:value="file.url"
									class="mt-4"
									label="Link"
									type="link"
									:href="file.url"
									readOnly
								/>
								<InputWithOverlappingLabel
									:value="String(formatBytes(file.size))"
									class="mt-4"
									label="Size"
									readOnly
								/>
								<InputWithOverlappingLabel :value="file.hash" class="mt-4" label="Hash" readOnly />
								<InputWithOverlappingLabel
									:value="dayjs(file.createdAt).format('MMMM D, YYYY h:mm A')"
									class="mt-4"
									label="Uploaded"
									readOnly
								/>
							</div>

							<!-- Albums section -->
							<div
								v-if="type === 'album' || type === 'uploads' || type === 'tag'"
								class="mb-8 max-w-[calc(100vw-12rem)]"
							>
								<h2 class="text-light-100">Albums</h2>
								<Combobox
									:data="albumsForCombobox"
									placeholder="Select album..."
									@selected="doAddFileToAlbum"
								></Combobox>

								<div>
									<Badge
										v-for="album in fileAlbums"
										:key="album.uuid"
										variant="default"
										class="text-sm mr-2 mt-2 bg-dark-100"
									>
										{{ album.name }}
										<span class="ml-2 cursor-pointer" @click="doRemoveFileFromAlbum(album.uuid)">
											<svg viewBox="0 0 14 14" class="h-3.5 w-3.5 stroke-white">
												<path d="M4 4l6 6m0-6l-6 6" />
											</svg>
										</span>
									</Badge>
								</div>
							</div>

							<!-- Tags -->
							<div
								v-if="type === 'album' || type === 'uploads' || type === 'tag'"
								class="mb-8 max-w-[calc(100vw-12rem)]"
							>
								<h2 class="text-light-100">Tags</h2>
								<TagBox
									:tags="tags"
									:fileTags="fileTags"
									@selected="doAddFileToTag"
									@tag:clicked="doRemoveFileFromTag"
								/>
							</div>

							<!-- User information section -->
							<div v-else class="mb-8 max-w-[calc(100vw-12rem)]">
								<h2 class="text-light-100">User info</h2>
								<InputWithOverlappingLabel
									:value="file.user?.username"
									class="mt-4"
									label="Username"
									readOnly
									type="link"
									:href="`/dashboard/admin/user/${file.user?.uuid}`"
								/>
								<InputWithOverlappingLabel
									:value="file.user?.uuid"
									class="mt-4"
									label="UUID"
									readOnly
								/>
								<InputWithOverlappingLabel
									:value="String(file.user?.enabled)"
									class="mt-4"
									label="Enabled"
									readOnly
								/>
								<InputWithOverlappingLabel
									:value="String(file.user?.roles.map((role: any) => role.name).join(', '))"
									class="mt-4"
									label="Roles"
									readOnly
								/>
								<InputWithOverlappingLabel
									:value="dayjs(file.user?.createdAt).format('MMMM D, YYYY h:mm A')"
									class="mt-4"
									label="Created at"
									readOnly
								/>
							</div>
							<!-- User information section -->
						</ScrollArea>
					</div>
				</div>
				<!-- File information panel -->
			</div>
		</DialogContent>
	</Dialog>
</template>

<script setup lang="ts">
import { useQueryClient, useMutation, useQuery } from '@tanstack/vue-query';
import { useClipboard } from '@vueuse/core';
import dayjs from 'dayjs';
import { ref, computed, nextTick, useSlots } from 'vue';
import { toast } from 'vue-sonner';
import Combobox from '@/components/combobox/Combobox.vue';
import TagBox from '@/components/tags/TagBox.vue';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTrigger } from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';
import { useAlbumsStore } from '@/store';
import { Album, FileWithAdditionalData, Tag, FilePropsType } from '@/types';
import ConfirmationDialog from '~/components/dialogs/ConfirmationDialog.vue';
import InputWithOverlappingLabel from '~/components/forms/InputWithOverlappingLabel.vue';
import {
	deleteFile,
	deleteFileAsAdmin,
	allowFileAsAdmin,
	quarantineFileAsAdmin,
	addFileToAlbum,
	removeFileFromAlbum,
	getFile,
	regenerateThumbnail,
	getTags,
	addFileToTag,
	removeFileFromTag
} from '~/use/api';
import { formatBytes, isFileVideo, isFileImage, isFileAudio } from '~/use/file';

interface Props {
	file: FileWithAdditionalData;
	type?: FilePropsType;
}

const props = withDefaults(defineProps<Props>(), {
	type: 'uploads'
});

const slots = useSlots();
const hasDefaultSlot = computed(() => Boolean(slots.default));

const albumsStore = useAlbumsStore();
const isAdmin = props.type === 'admin' || props.type === 'quarantine';
const fileAlbums = ref<Album[]>([]);
const fileTags = ref<Tag[]>([]);
const fileElement = ref<HTMLElement | null>(null);
const isVerticalImage = ref(false);

const onImageLoad = async () => {
	if (!fileElement.value) return;
	await nextTick();
	isVerticalImage.value = fileElement.value.clientHeight > fileElement.value.clientWidth;
};

const queryClient = useQueryClient();

const { mutate: mutateDeleteFile } = useMutation({
	mutationFn: (uuid: string) => (isAdmin ? deleteFileAsAdmin(uuid) : deleteFile(uuid))
});

const { mutate: mutateQuarantineFile } = useMutation({
	mutationFn: (uuid: string) => quarantineFileAsAdmin(uuid)
});

const { mutate: mutateAllowFile } = useMutation({
	mutationFn: (uuid: string) => allowFileAsAdmin(uuid)
});

const { mutate: mutateRegenerateThumbnail } = useMutation({
	mutationFn: (uuid: string) => regenerateThumbnail(uuid)
});

const onOpen = async (isOpen: boolean) => {
	if (!isOpen) return;
	void albumsStore.get();
	void getFileInformation();
};

const getFileInformation = async () => {
	if (props.type === 'admin') return;
	const file = await getFile(props.file.uuid);
	fileAlbums.value = file.albums;
	fileTags.value = file.tags;
};

const albumsForCombobox = computed(() => {
	return albumsStore.albums
		.filter(album => !fileAlbums.value.some(fileAlbum => fileAlbum.uuid === album.uuid))
		.map(album => ({
			value: album.uuid,
			label: album.name
		}));
});

const { copy } = useClipboard();
const isCopying = ref(false);

const doAddFileToAlbum = async (uuid: string) => {
	await addFileToAlbum(props.file.uuid, uuid);
	await getFileInformation();
};

const doRemoveFileFromAlbum = async (uuid: string) => {
	await removeFileFromAlbum(props.file.uuid, uuid);
	await getFileInformation();
};

const doAddFileToTag = async ({ uuid, name }: { uuid: string; name: string }) => {
	await addFileToTag(props.file.uuid, uuid);
	queryClient.invalidateQueries({ queryKey: ['tags'] });
	fileTags.value.push({ uuid, name });
};

const doRemoveFileFromTag = async ({ uuid }: { uuid: string }) => {
	await removeFileFromTag(props.file.uuid, uuid);
	fileTags.value = fileTags.value.filter(tag => tag.uuid !== uuid);
};

const copyLink = () => {
	if (isCopying.value) return;
	isCopying.value = true;

	if (props.file?.url) void copy(props.file?.url);
	// eslint-disable-next-line no-restricted-globals
	setTimeout(() => (isCopying.value = false), 1000);
};

const doQuarantineFile = () => {
	mutateQuarantineFile(props.file.uuid, {
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: ['admin', 'files'] });
			toast.success('File quarantined');
		}
	});
};

const doAllowFile = () => {
	mutateAllowFile(props.file.uuid, {
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: ['admin', 'files'] });
			toast.success('File allowed');
		}
	});
};

const doDeleteFile = () => {
	mutateDeleteFile(props.file.uuid, {
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: isAdmin ? ['admin', 'files'] : ['files'] });
			toast.success('File deleted');
		}
	});
};

const doRegenerateThumbnail = () => {
	mutateRegenerateThumbnail(props.file.uuid, {
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: isAdmin ? ['admin', 'files'] : ['files'] });
			toast.success('Thumbnail regenerated');
		}
	});
};

const { data: tags } = useQuery({
	queryKey: ['tags'],
	queryFn: async () => {
		const data = await getTags();
		return data.sort((a: any, b: any) => {
			return b._count.files - a._count.files;
		});
	},
	placeholderData: (previousData: any) => previousData
});
</script>

// packages/next/src/components/dialogs/FileInformationDialog.tsx
'use client';

import { useCallback, useEffect, useState, type PropsWithChildren } from 'react';
import type { Album as AlbumType, FilePropsType, FileWithAdditionalData, Tag } from '@/types';
import type { DialogProps } from '@radix-ui/react-dialog';
import {
	MediaControlBar,
	MediaController,
	MediaFullscreenButton,
	MediaMuteButton,
	MediaPipButton,
	MediaPlaybackRateButton,
	MediaPlayButton,
	MediaTimeDisplay,
	MediaTimeRange,
	MediaVolumeRange
} from 'media-chrome/dist/react';

import { formatBytes, isFileAudio, isFileImage, isFileVideo } from '@/lib/file';
import request from '@/lib/request';
import { cn } from '@/lib/utils';
import { Dialog, DialogContent } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { FancyMultiSelect } from '@/components/FancyMultiSelect';
import { FileInformationDialogActions } from '@/components/FileInformationDialogActions';
import { FileInformationDrawerActions } from '@/components/FileInformationDrawerActions';
import { ArrowUpRightFromSquare, FileQuestionIcon } from 'lucide-react';
import { Badge } from '../ui/badge';
import Link from 'next/link';
import { getDate } from '@/lib/time';
import { toast } from 'sonner';

export function FileInformationDialog({
	file,
	type,
	isOpen = false,
	onOpenChange = () => {}
}: PropsWithChildren<{
	readonly file: FileWithAdditionalData;
	readonly isOpen: DialogProps['open'];
	readonly onOpenChange: DialogProps['onOpenChange'];
	readonly type: FilePropsType;
}>) {
	const [albums, setAlbums] = useState<AlbumType[]>([]);
	const [tags, setTags] = useState<Tag[]>([]);
	const [fileAlbums, setFileAlbums] = useState<AlbumType[]>([]);
	const [fileTags, setFileTags] = useState<Tag[]>([]);

	const fetchExtraData = useCallback(async () => {
		try {
			if (type === 'admin') return;
			if (type === 'publicAlbum') return;

			const { data: createdAlbums, error: createdAlbumError } = await request.get({
				url: 'albums'
			});
			if (createdAlbumError) {
				toast.error(createdAlbumError);
				return;
			}

			setAlbums(createdAlbums.albums);

			const { data: albumsTags, error: albumsTagsError } = await request.get({ url: 'tags' });
			setTags(albumsTags.tags);
			if (albumsTagsError) {
				toast.error(albumsTagsError);
				return;
			}

			const { data: fileInfo, error: fileInfoError } = await request.get({ url: `file/${file.uuid}` });
			if (fileInfoError) {
				toast.error(fileInfoError);
				return;
			}

			setFileAlbums(fileInfo.file.albums);
			setFileTags(fileInfo.file.tags);
		} catch (error) {
			console.error(error);
		}
	}, [file.uuid, type]);

	const addFileToAlbum = useCallback(
		async (albumUuid: string) => {
			try {
				const { error } = await request.post({
					url: `file/${file.uuid}/album/${albumUuid}`
				});
				if (error) {
					toast.error(error);
					return;
				}

				toast.success('File added to album');
			} catch (error: any) {
				toast.error(error);
			}
		},
		[file.uuid]
	);

	const removeFileFromAlbum = useCallback(
		async (albumUuid: string) => {
			try {
				const { error } = await request.delete({
					url: `file/${file.uuid}/album/${albumUuid}`
				});
				if (error) {
					toast.error(error);
					return;
				}

				toast.success('File removed from album');
			} catch (error) {
				console.error(error);
			}
		},
		[file.uuid]
	);

	const addTagToFile = useCallback(
		async (tagUuid: string) => {
			try {
				const { error } = await request.post({
					url: `file/${file.uuid}/tag/${tagUuid}`
				});
				if (error) {
					toast.error(error);
					return;
				}

				toast.success('Tag added to file');
			} catch (error: any) {
				toast.error(error);
			}
		},
		[file.uuid]
	);

	const removeTagFromFile = useCallback(
		async (tagUuid: string) => {
			try {
				const { error } = await request.delete({
					url: `file/${file.uuid}/tag/${tagUuid}`
				});
				if (error) {
					toast.error(error);
					return;
				}

				toast.success('Tag removed from file');
			} catch (error) {
				console.error(error);
			}
		},
		[file.uuid]
	);

	useEffect(() => {
		if (isOpen) void fetchExtraData();
	}, [isOpen, fetchExtraData]);

	return (
		<Dialog open={isOpen} onOpenChange={onOpenChange}>
			<DialogContent
				className={cn(
					// isVertical ? '!w-fit' : '!w-max',
					'max-w-[calc(100vw-8rem)] max-h-[calc(100vh-8rem)] min-h-[calc(100vh-11rem)] !w-max p-0'
				)}
			>
				<div className="absolute right-0 -bottom-12 z-10 md:inline-block hidden">
					<FileInformationDialogActions file={file} type={type} />
				</div>

				<div className="absolute right-0 -bottom-12 z-10 md:hidden inline-block">
					<FileInformationDrawerActions file={file} type={type} />
				</div>

				<Tabs
					defaultValue={
						isFileImage(file) || isFileAudio(file) || isFileVideo(file) ? 'preview' : 'information'
					}
					className="relative"
				>
					{type === 'publicAlbum' ? null : (
						<div className="flex justify-center w-full absolute -top-12">
							<TabsList>
								<TabsTrigger value="preview">Preview</TabsTrigger>
								<TabsTrigger value="information">Information</TabsTrigger>
							</TabsList>
						</div>
					)}
					<TabsContent value="preview" className="mt-0">
						<div className={cn('h-[calc(100vh-11rem)]', 'w-full')}>
							{isFileImage(file) ? (
								<picture>
									<img src={file.url} className="h-full object-contain md:block" />
								</picture>
							) : isFileVideo(file) ? (
								<MediaController className="h-full hidden md:block">
									<video slot="media" src={file.url} crossOrigin="" className="h-full" />
									<MediaControlBar>
										<MediaPlayButton />
										<MediaMuteButton />
										<MediaVolumeRange />
										<MediaTimeRange />
										<MediaPipButton />
										<MediaFullscreenButton />
									</MediaControlBar>
								</MediaController>
							) : isFileAudio(file) ? (
								<MediaController className="h-full hidden md:block">
									<audio slot="media" src={file.url} crossOrigin="" />
									<MediaControlBar>
										<MediaPlayButton />
										<MediaTimeDisplay showDuration />
										<MediaTimeRange />
										<MediaPlaybackRateButton />
										<MediaMuteButton />
										<MediaVolumeRange />
									</MediaControlBar>
								</MediaController>
							) : (
								<span className="text-light-100 h-full items-center hidden md:flex px-8 flex-col justify-center gap-4">
									<FileQuestionIcon className="w-16 h-16" />
									Sorry but this filetype can't be previewed at this time.
								</span>
							)}
						</div>
					</TabsContent>
					<TabsContent value="information">
						{isFileImage(file) ? (
							<picture>
								<img
									src={file.url}
									className="h-auto hidden absolute -top-px -left-[272px] xl:block border bg-background p-2 shadow-lg sm:rounded-lg max-w-[264px]"
								/>
							</picture>
						) : isFileVideo(file) ? (
							<video
								className="h-auto hidden absolute -top-px -left-[272px] xl:block border bg-background p-2 shadow-lg sm:rounded-lg max-w-[264px]"
								autoPlay
								loop
								muted
							>
								<source src={file.preview} type="video/mp4" />
							</video>
						) : null}
						<ScrollArea className="max-h-[calc(100vh-8rem)] w-full">
							<div className={cn('grid grid-rows-1 gap-8 md:p-8 p-2 min-w-96 md:grid-cols-2')}>
								<div className="flex flex-col space-y-1.5 gap-0">
									<h2 className="text-2xl font-semibold leading-none tracking-tight mb-4">
										File information
									</h2>

									<div>
										<Label htmlFor="uuid">UUID</Label>
										<Input value={file.uuid} name="uuid" id="uuid" readOnly />
									</div>

									<div>
										<Label htmlFor="name">Name</Label>
										<Input value={file.name} name="name" id="name" readOnly />
									</div>

									<div>
										<Label htmlFor="original">Original</Label>
										<Input value={file.original} name="original" id="original" readOnly />
									</div>

									<div>
										<Label htmlFor="ip">
											IP{' '}
											{type === 'admin' ? (
												<Link
													href={`/dashboard/admin/ip/${file.ip}`}
													className="text-blue-500 underline inline-flex items-center ml-2"
												>
													view files <ArrowUpRightFromSquare className="w-3 h-3 ml-1" />
												</Link>
											) : null}
										</Label>
										<Input value={file.ip} name="ip" id="ip" readOnly />
									</div>

									<div>
										<Label htmlFor="url">URL</Label>
										<Input value={file.url} name="url" id="url" readOnly />
									</div>

									<div>
										<Label htmlFor="size">Size</Label>
										<Input value={formatBytes(file.size)} name="size" id="size" readOnly />
									</div>

									<div>
										<Label htmlFor="hash">Hash</Label>
										<Input value={file.hash} name="hash" id="hash" readOnly />
									</div>

									<div>
										<Label htmlFor="uploaded">Uploaded</Label>
										<Input value={getDate(file.createdAt)} name="uploaded" id="uploaded" readOnly />
									</div>
								</div>

								{type === 'admin' && file.user ? (
									<div className="flex flex-col space-y-1.5 gap-0">
										<h2 className="text-2xl font-semibold leading-none tracking-tight mb-4">
											User information
										</h2>

										<div>
											<Label htmlFor="owner">
												Owner
												<Link
													href={`/dashboard/admin/users/${file.user?.uuid}`}
													className="text-blue-500 underline inline-flex items-center ml-2"
												>
													view files <ArrowUpRightFromSquare className="w-3 h-3 ml-1" />
												</Link>
											</Label>
											<Input value={file.user.username} name="owner" id="owner" readOnly />
										</div>

										<div>
											<Label htmlFor="userUUID">User UUID</Label>
											<Input value={file.user?.uuid} name="userUUID" id="userUUID" readOnly />
										</div>

										<div>
											<Label htmlFor="status">Status</Label>
											<Input
												value={file.user.enabled ? 'Enabled' : 'Disabled'}
												name="status"
												id="status"
												readOnly
											/>
										</div>

										<div>
											<Label htmlFor="null">Roles</Label>
											<div>
												{file.user.roles.map((role: any) => (
													<Badge key={role.name} className="mr-1">
														{role.name}
													</Badge>
												))}
											</div>
										</div>

										<div>
											<Label htmlFor="joined">Joined</Label>
											<Input
												value={getDate(file.user.createdAt.toString())}
												name="joined"
												id="joined"
												readOnly
											/>
										</div>
									</div>
								) : (
									<div className="max-w-96">
										<div className="flex flex-col space-y-1.5 gap-0">
											<h2 className="text-2xl font-semibold leading-none tracking-tight mb-4">
												Albums
											</h2>
											<div>
												<Label htmlFor="albums">Add albums</Label>
												<div className="font-light text-xs px-2 my-2 border-l-2 border-blue-500">
													A file can be added to multiple albums.
												</div>
												<FancyMultiSelect
													name="albums"
													placeholder="Select album..."
													options={
														albums
															? albums.map(album => ({
																	value: album.uuid,
																	label: album.name
																}))
															: []
													}
													initialSelected={fileAlbums.map(album => album.uuid)}
													onSelected={async value => addFileToAlbum(value)}
													onRemoved={async value => removeFileFromAlbum(value)}
												/>
											</div>
										</div>
										<div className="flex flex-col space-y-1.5 gap-0 mt-8">
											<h2 className="text-2xl font-semibold leading-none tracking-tight mb-4">
												Tags
											</h2>
											<div>
												<Label htmlFor="tags">Attach tags</Label>
												<div className="font-light text-xs px-2 my-2 border-l-2 border-blue-500">
													To create a new tag you can type the name of the tag and press enter
													and it will be attached to the file automatically.
												</div>

												<FancyMultiSelect
													name="tags"
													placeholder="Select tags..."
													options={
														tags
															? tags.map(tag => ({
																	value: tag.uuid,
																	label: tag.name
																}))
															: []
													}
													initialSelected={fileTags.map(tag => tag.uuid)}
													onSelected={async value => addTagToFile(value)}
													onRemoved={async value => removeTagFromFile(value)}
												/>
											</div>
										</div>
									</div>
								)}
							</div>
						</ScrollArea>
					</TabsContent>
				</Tabs>
			</DialogContent>
		</Dialog>
	);
}
