// packages/next/src/components/dialogs/AlbumSettingsDialog.tsx
'use client';

import { useEffect, type PropsWithChildren } from 'react';
import { updateAlbumSettings } from '@/actions/UpdateAlbumSettings';
import type { AlbumLink } from '@/types';
import { MessageType } from '@/types';
import { useAtom, useAtomValue } from 'jotai';
import { useFormState } from 'react-dom';
import { toast } from 'sonner';

import { isDialogOpenAtom, selectedAlbumAtom } from '@/lib/atoms/albumSettingsDialog';
import { Button } from '@/components/ui/button';
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
	DialogTrigger
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';

import { AlbumSettingsDialogActions } from '../AlbumSettingsDialogActions';
import { AlbumLinksTable } from '../tables/album-links-table/AlbumLinksTable';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import request from '@/lib/request';
// import { AlbumLinkCreateForm } from '../tables/album-links-table/AlbumLinkCreateForm';
import { Plus } from 'lucide-react';

export function AlbumSettingsDialog({ children }: PropsWithChildren<{}>) {
	const [open, setOpen] = useAtom(isDialogOpenAtom);
	const album = useAtomValue(selectedAlbumAtom);
	const queryClient = useQueryClient();

	const [state, formAction] = useFormState(updateAlbumSettings, {
		message: '',
		type: MessageType.Uninitialized
	});

	const createNewAlbumLink = async () => {
		try {
			await request.post(`album/${album?.uuid}/link`, {});

			toast.success('Link created');
			void queryClient.invalidateQueries({ queryKey: ['albums', 'links'] });
		} catch (error: any) {
			toast.error(error);
		}
	};

	const { data, error } = useQuery<{ links: AlbumLink[] }>({
		queryKey: ['albums', 'links'],
		enabled: Boolean(album?.uuid),
		queryFn: async () => {
			const {
				data: response,
				error,
				status
			} = await request.get(
				`album/${album?.uuid}/links`,
				{},
				{},
				{
					next: {
						tags: ['links']
					}
				}
			);

			if (error && status === 401) {
				throw new Error(error);
			}

			return response;
		}
	});

	useEffect(() => {
		if (state.type === MessageType.Error) toast.error(state.message);
		else if (state.type === MessageType.Success) {
			toast.success(state.message);
			setOpen(false);
		}

		return () => {
			if (state.type === MessageType.Success) {
				state.type = MessageType.Uninitialized;
				state.message = '';
			}
		};
	}, [setOpen, state, state.message, state.type]);

	if (error) {
		toast.error(error.message);
	}

	return (
		<Dialog open={open} onOpenChange={setOpen}>
			<DialogTrigger asChild>{children}</DialogTrigger>
			<DialogContent className="">
				<DialogHeader>
					<DialogTitle>Album settings</DialogTitle>
					<DialogDescription>Manage settings and create new public links</DialogDescription>
				</DialogHeader>

				<form action={formAction} className="flex flex-col space-y-1.5 gap-2">
					<input type="hidden" name="uuid" value={album?.uuid} />
					<div>
						<Label htmlFor="name">Name</Label>
						<Input id="name" name="name" defaultValue={album?.name} />
					</div>
					<div>
						<Label htmlFor="description">Description</Label>
						<Textarea id="description" name="description" defaultValue={album?.description} />
					</div>
					<div className="space-y-2 flex flex-row items-center justify-between rounded-lg border p-3 shadow-sm">
						<div className="space-y-0.5">
							<Label
								className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
								htmlFor="nsfw"
							>
								NSFW Album
							</Label>
							<p className="text-[0.8rem] text-muted-foreground">
								Activate if you want to blur the contents by default.
							</p>
						</div>
						<Switch id="nsfw" name="nsfw" defaultChecked={album?.nsfw ?? false} />
					</div>
				</form>
				<div>
					<Label htmlFor="description">Links</Label>
					<p className="text-[0.8rem] text-muted-foreground">
						A list of all the links created for this album. Each link is unique and will remain private
						unless you share it with the world.
					</p>

					{/* <AlbumLinkCreateForm albumUuid={album?.uuid} /> */}
					<Button
						type="submit"
						variant="secondary"
						className="mt-2"
						onClick={async () => createNewAlbumLink()}
					>
						<Plus className="mr-2 h-4 w-4" />
						Create new link
					</Button>

					<AlbumLinksTable data={data?.links} />
				</div>
				<DialogFooter className="!justify-between">
					<AlbumSettingsDialogActions />
					<Button type="submit">Save</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}

// packages/frontend/src/components/dialogs/AlbumSettingsDialog.vue
<template>
	<Dialog @update:open="onOpen">
		<DialogTrigger><slot /></DialogTrigger>
		<DialogContent>
			<DialogHeader>
				<DialogTitle>Album settings</DialogTitle>
			</DialogHeader>

			<div class="flex items-center space-x-2 mt-4">
				<Switch id="nsfw" :checked="album.nsfw" @click="setNsfw" />
				<Label for="nsfw">NSFW album</Label>
			</div>
			<div class="flex w-full max-w-sm items-end space-x-2">
				<InputWithLabel v-model="albumName" label="Album name" name="name" />
				<Button type="button" @click="setNewAlbumName">Rename</Button>
			</div>

			<DialogHeader class="mt-4">
				<DialogTitle>Album links</DialogTitle>
				<DialogDescription>
					A list of all the links created for this album. Each link is unique and will remain private unless
					you share it with the world.
				</DialogDescription>
				<Button type="button" @click="createLink">Create new link</Button>
			</DialogHeader>

			<div v-if="isLoadingLinks" class="space-y-2 mt-2">
				<Skeleton class="h-4 w-[250px]" />
				<Skeleton class="h-4 w-[200px]" />
			</div>
			<AlbumLinksTable v-else :albumUuid="album.uuid" :data="links" />

			<DialogFooter>
				<ConfirmationDialog
					title="Delete album"
					message="This action will delete the album and every public link associated with it. All uploaded files will remain intact. Are you sure?"
					:callback="() => doDeleteAlbum()"
				>
					<Button type="button" variant="destructive">Delete album</Button>
				</ConfirmationDialog>
				<ConfirmationDialog
					title="Delete album"
					message="This action will delete the album and ALL files associated with it, even if they are part of other albums so this action is not reversible. Are you sure?"
					:callback="() => doPurgeAlbum()"
				>
					<Button type="button" variant="destructive">Delete album and all files</Button>
				</ConfirmationDialog>
			</DialogFooter>
		</DialogContent>
	</Dialog>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useAlbumsStore } from '~/store';
import { createAlbumLink, updateAlbum, deleteAlbum, purgeAlbum } from '~/use/api';
import { toast } from 'vue-sonner';
import { Album } from '@/types';
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
	DialogTrigger
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import InputWithLabel from '@/components/input/InputWithLabel.vue';
import AlbumLinksTable from '@/components/table/AlbumLinksTable.vue';
import ConfirmationDialog from '@/components/dialogs/ConfirmationDialog.vue';

const props = defineProps<{
	album: Album;
}>();

const albumsStore = useAlbumsStore();
const links = computed(() => albumsStore.currentAlbumLinks);
const isLoadingLinks = ref(false);

// eslint-disable-next-line vue/no-setup-props-destructure
const albumName = ref(props.album.name);
// eslint-disable-next-line vue/no-setup-props-destructure
const isNsfw = ref(props.album.nsfw);

const onOpen = async (isOpen: boolean) => {
	if (!isOpen) return;
	isLoadingLinks.value = true;
	albumName.value = props.album.name;
	isNsfw.value = props.album.nsfw;
	await albumsStore.getAlbumLinks(props.album.uuid);
	isLoadingLinks.value = false;
};

const setNsfw = async () => {
	isNsfw.value = !isNsfw.value;
	await updateAlbum(props.album.uuid, {
		name: 'nsfw',
		value: isNsfw.value
	});
};

const createLink = async () => {
	const newLink = await createAlbumLink(props.album.uuid);
	albumsStore.currentAlbumLinks.push(newLink.data);
	toast.success('New link created');
};

const setNewAlbumName = async () => {
	if (!albumName.value) {
		toast.error('Album name cannot be empty');
		return;
	}

	await updateAlbum(props.album.uuid, {
		name: 'name',
		value: albumName.value
	});
	toast.success('Changed album name');
};

const doDeleteAlbum = async () => {
	await deleteAlbum(props.album.uuid);
	albumsStore.albums = albumsStore.albums.filter(a => a.uuid !== props.album.uuid);
	toast.success('Album deleted');
};

const doPurgeAlbum = async () => {
	await purgeAlbum(props.album.uuid);
	albumsStore.albums = albumsStore.albums.filter(a => a.uuid !== props.album.uuid);
	toast.success('Album purged');
};
</script>
