// packages/next/src/components/tables/invites-table/InvitesTable.tsx
'use client';

import type { ColumnFiltersState, SortingState, VisibilityState } from '@tanstack/react-table';
import {
	createColumnHelper,
	getCoreRowModel,
	getFilteredRowModel,
	getSortedRowModel,
	useReactTable
} from '@tanstack/react-table';
import { useState, type PropsWithChildren } from 'react';
import { DataTable } from '../DataTable';
import dayjs from 'dayjs';
import type { Invite } from '@/types';
import { Button } from '@/components/ui/button';
import { InvitesConfirmationAction } from './InvitesConfirmationAction';

const columnHelper = createColumnHelper<Invite>();
const columns = [
	columnHelper.accessor(row => row.code, {
		id: 'code',
		header: 'Code',
		cell(props) {
			return (
				<a href={`/invite/${props.row.original.code}`} className="text-blue-500 underline">
					{props.row.original.code}
				</a>
			);
		}
	}),
	columnHelper.accessor(row => (row.used ? 'Used' : 'Available'), {
		id: 'status',
		header: 'Status'
	}),
	columnHelper.accessor(row => row.createdBy.username, {
		id: 'createdBy',
		header: 'Created By',
		cell(props) {
			return (
				<a href={`/admin/users/${props.row.original.createdBy.uuid}`} className="text-blue-500 underline">
					{props.row.original.createdBy.username}
				</a>
			);
		}
	}),
	columnHelper.accessor(row => dayjs(row.createdAt).format('MMMM D, YYYY h:mm A'), {
		id: 'createdAt',
		header: 'Created At'
	}),
	columnHelper.accessor(row => row.usedBy.username, {
		id: 'claimedBy',
		header: 'Claimed By',
		cell(props) {
			return props.row.original.usedBy.uuid ? (
				<a href={`/admin/users/${props.row.original.usedBy.uuid}`} className="text-blue-500 underline">
					{props.row.original.usedBy.username}
				</a>
			) : (
				'N/A'
			);
		}
	}),
	columnHelper.accessor(row => (row.editedAt ? dayjs(row.editedAt).format('MMMM D, YYYY h:mm A') : 'N/A'), {
		id: 'claimedAt',
		header: 'Claimed At'
	}),
	columnHelper.display({
		id: 'actions',
		header: '',
		cell: props => (
			<div className="flex justify-end">
				<InvitesConfirmationAction
					code={props.row.original.code}
					description="Are you sure you want to revoke this invite? It will prevent anyone from using it to create an account."
				>
					<Button variant="destructive">Revoke</Button>
				</InvitesConfirmationAction>
			</div>
		)
	})
];

export const InvitesTable = ({ data }: PropsWithChildren<{ readonly data: any }>) => {
	const [sorting, setSorting] = useState<SortingState>([]);
	const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([]);
	const [columnVisibility, setColumnVisibility] = useState<VisibilityState>({});
	const table = useReactTable({
		data,
		columns,
		getCoreRowModel: getCoreRowModel(),
		onSortingChange: setSorting,
		getSortedRowModel: getSortedRowModel(),
		onColumnFiltersChange: setColumnFilters,
		getFilteredRowModel: getFilteredRowModel(),
		onColumnVisibilityChange: setColumnVisibility,
		state: {
			sorting,
			columnFilters,
			columnVisibility
		}
	});

	return <DataTable table={table} columns={columns} />;
};

// packages/frontend/src/components/table/InvitesTable.vue
<template>
	<Table>
		<TableHeader>
			<TableRow>
				<TableHead class="text-center">Code</TableHead>
				<TableHead class="text-center">Status</TableHead>
				<TableHead class="text-center">Created by</TableHead>
				<TableHead class="text-center">Created at</TableHead>
				<TableHead class="text-center">Claimed by</TableHead>
				<TableHead class="text-center">Claimed at</TableHead>
				<TableHead class="text-right" />
			</TableRow>
		</TableHeader>
		<TableBody>
			<TableRow v-for="invite in invites" :key="invite.code">
				<TableCell>
					<a :href="`/invite/${invite.code}`" target="_blank" rel="noopener noreferrer">{{ invite.code }}</a>
				</TableCell>
				<TableCell>
					{{ invite.used ? 'Used' : 'Available' }}
				</TableCell>
				<TableCell>
					{{ invite.createdBy.username }}
				</TableCell>
				<TableCell>
					{{ dayjs(invite.createdAt).format('MMMM D, YYYY h:mm A') }}
				</TableCell>
				<TableCell>
					{{ invite.usedBy ? invite.usedBy.username : 'N/A' }}
				</TableCell>
				<TableCell>
					{{ invite.editedAt ? dayjs(invite.editedAt).format('MMMM D, YYYY h:mm A') : 'N/A' }}
				</TableCell>
				<TableCell class="flex justify-end">
					<ConfirmationDialog
						title="Revoke link"
						message="This action will revoke the link preventing anyone from using it to create an account."
						:callback="() => cancelInvite(invite.code)"
					>
						<Button v-if="!invite.used" variant="destructive"> Revoke </Button>
					</ConfirmationDialog>
				</TableCell>
			</TableRow>
		</TableBody>
	</Table>
</template>

<script setup lang="ts">
import type { Invite } from '@/types';
import { cancelInvite } from '~/use/api';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import ConfirmationDialog from '@/components/dialogs/ConfirmationDialog.vue';
import { Button } from '@/components/ui/button';

import dayjs from 'dayjs';

defineProps<{
	invites: Invite[];
}>();
</script>
