// frontend/src/components/header/Header.vue
<template>
	<div class="flex w-full h-12 items-center mt-8">
		<router-link to="/">
			<img src="../../assets/images/logo.png" alt="chibisafe logo" class="w-12 mr-2" />
		</router-link>
		<router-link to="/">
			<span class="font-bold text-3xl">chibisafe</span>
		</router-link>
		<span class="flex-1" />
		<Auth />
		<span class="ml-4">
			<a href="https://discord.gg/5g6vgwn" rel="noopener noreferrer" target="_blank" class="hover:text-blue-400"
				><IconDiscord class="w-8 h-8"
			/></a>
		</span>
		<span class="ml-4">
			<a
				href="https://github.com/WeebDev/chibisafe"
				rel="noopener noreferrer"
				target="_blank"
				class="hover:text-blue-400"
				><IconGitHub class="w-8 h-8"
			/></a>
		</span>
	</div>
</template>

<script setup lang="ts">
import Auth from '../auth/Auth.vue';
// @ts-ignore
import IconGitHub from '~icons/carbon/logo-github';
// @ts-ignore
import IconDiscord from '~icons/carbon/logo-discord';
</script>

// packages/next/src/components/Header.tsx
import Link from 'next/link';

import { buttonVariants } from '@/components/ui/button';
import { Navigation } from '@/components/Navigation';
import { NavigationUser } from '@/components/NavigationUser';
import { DiscordLogo } from '@/components/svg/DiscordLogo';
import { GitHubLogo } from '@/components/svg/GitHubLogo';
import { PatreonLogo } from '@/components/svg/PatreonLogo';

export const Header = () => {
	return (
		<header className="container z-40 bg-background">
			<div className="flex h-20 items-center justify-between py-6">
				<Navigation />
				<nav className="flex items-center">
					<Link href="https://discord.gg/5g6vgwn" target="_blank" rel="noreferrer">
						<div
							className={buttonVariants({
								size: 'icon',
								variant: 'ghost'
							})}
						>
							<DiscordLogo className="h-6 w-6" />
							<span className="sr-only">Discord</span>
						</div>
					</Link>

					<Link href="https://github.com/chibisafe/chibisafe" target="_blank" rel="noreferrer">
						<div
							className={buttonVariants({
								size: 'icon',
								variant: 'ghost'
							})}
						>
							<GitHubLogo className="h-6 w-6" />
							<span className="sr-only">GitHub</span>
						</div>
					</Link>

					<Link href="https://patreon.com/pitu" target="_blank" rel="noreferrer">
						<div
							className={buttonVariants({
								size: 'icon',
								variant: 'ghost'
							})}
						>
							<PatreonLogo className="h-6 w-6" />
							<span className="sr-only">Patreon</span>
						</div>
					</Link>
					<NavigationUser />
				</nav>
			</div>
		</header>
	);
};
