// packages/frontend/src/components/tooltip/Tooltip.vue
<template>
	<TooltipProvider>
		<Tooltip>
			<TooltipTrigger>
				<slot />
			</TooltipTrigger>
			<TooltipContent>
				<p>{{ text }}</p>
			</TooltipContent>
		</Tooltip>
	</TooltipProvider>
</template>

<script setup lang="ts">
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
defineProps<{
	text: string;
}>();
</script>

// packages/next/src/components/Tooltip.tsx
import { Tooltip as TooltipWrapper, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import type { PropsWithChildren } from 'react';

export function Tooltip({ children, content }: PropsWithChildren<{ readonly content: string }>) {
	return (
		<TooltipProvider delayDuration={100}>
			<TooltipWrapper>
				<TooltipTrigger asChild>{children}</TooltipTrigger>
				<TooltipContent className="bg-primary text-primary-foreground">
					<p>{content}</p>
				</TooltipContent>
			</TooltipWrapper>
		</TooltipProvider>
	);
}
