// packages/next/src/components/ui/button.tsx
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';

import { cn } from '@/lib/utils';

const buttonVariants = cva(
	'inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none ring-offset-background',
	{
		variants: {
			variant: {
				default: 'bg-primary text-primary-foreground hover:bg-primary/90',
				destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
				outline: 'border border-input hover:bg-accent hover:text-accent-foreground',
				secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
				ghost: 'hover:bg-accent hover:text-accent-foreground',
				link: 'underline-offset-4 hover:underline text-primary'
			},
			size: {
				default: 'h-10 py-2 px-4',
				sm: 'h-9 px-3 rounded-md',
				lg: 'h-11 px-8 rounded-md',
				icon: 'h-10 w-10'
			}
		},
		defaultVariants: {
			variant: 'default',
			size: 'default'
		}
	}
);

export interface ButtonProps
	extends React.ButtonHTMLAttributes<HTMLButtonElement>,
		VariantProps<typeof buttonVariants> {
	readonly asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
	({ className, variant, size, asChild = false, ...props }, ref) => {
		const Comp = asChild ? Slot : 'button';
		return <Comp className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />;
	}
);
Button.displayName = 'Button';

export { Button, buttonVariants };

// packages/frontend/src/components/buttons/Button.vue
<template>
	<button type="button" class="" :class="[getVariant, getAlign, getSize, getType]">
		<slot />
	</button>
</template>

<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps({
	variant: {
		type: String,
		default: 'primary'
	},
	size: {
		type: String,
		default: 'md'
	},
	align: {
		type: String,
		default: 'center'
	},
	type: {
		type: String,
		default: 'none'
	}
});

const getVariant = computed(() => {
	if (props.variant === 'link') {
		return 'inline-flex font-medium focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-blue-500 bg-transparent hover:bg-transparent text-light-100 hover:text-white border-transparent p-0';
	}

	return 'border focus:ring-0 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center focus:ring-gray-600 bg-dark-110 border-gray-700 text-white hover:bg-dark-100 mr-2 mb-2';
});

const getSize = computed(() => {
	return `text-${props.size}`;
});

const getAlign = computed(() => {
	if (props.align === 'left') {
		return 'justify-start';
	} else if (props.align === 'right') {
		return 'justify-end';
	}

	return 'justify-center';
});

const getType = computed(() => {
	if (props.type === 'success') {
		return 'bg-green-700 hover:bg-green-600';
	}

	return '';
});
</script>
