// packages/frontend/src/pages/dashboard/snippets/[uuid].vue
<template>
	<Sidebar>
		<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
			<Breadcrumbs
				:pages="[
					{
						name: 'Snippets',
						href: '/dashboard/snippets'
					},
					{
						name: snippet?.name ?? 'Loading...',
						href: '/dashboard/snippets/' + props.uuid
					}
				]"
			/>
			<h1 class="text-2xl mt-8 font-semibold text-light-100">{{ snippet?.name ?? 'Loading...' }}</h1>
			<div v-if="snippet" class="my-4 h-automobile:py-2 flex mobile:flex-wrap flex-col">
				<div class="w-full flex-1 mb-4">
					<div class="flex items-center">
						<div class="mb-2">
							<p class="text-light-100">Name: {{ snippet.name }}</p>
							<p class="text-light-100">Created: {{ dayjs(snippet.createdAt).fromNow() }}</p>
						</div>
						<div class="flex-1"></div>
						<div class="mb-2">
							<a
								:href="snippet.link"
								target="_blank"
								rel="noopener noreferrer"
								class="text-blue-400 hover:text-blue-500 transition-colors duration-200"
							>
								Open snippet
							</a>
							<a
								:href="snippet.raw"
								target="_blank"
								rel="noopener noreferrer"
								class="text-blue-400 hover:text-blue-500 transition-colors duration-200 ml-4"
							>
								Open raw
							</a>
						</div>
					</div>
					<div class="relative">
						<span
							class="bg-black/30 absolute top-0 right-0 uppercase font-bold text-xs rounded-bl-md px-2 py-1 text-light-100"
						>
							{{ snippet.language }}
						</span>
						<component :is="hljsVuePlugin.component" :language="snippet.language" :code="snippet.content" />
					</div>
				</div>
			</div>
		</div>
	</Sidebar>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { getSnippet } from '~/use/api';
import type { Snippet } from '~/types';
import Sidebar from '~/components/sidebar/Sidebar.vue';
import Breadcrumbs from '~/components/breadcrumbs/Breadcrumbs.vue';
import 'highlight.js/styles/github-dark.css';
import hljsVuePlugin from '@highlightjs/vue-plugin';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

const props = defineProps<{
	uuid: string;
}>();

dayjs.extend(relativeTime);
const snippet = ref<Snippet>();

onMounted(async () => {
	snippet.value = await getSnippet(props.uuid);
});
</script>

// packages/next/src/app/dashboard/snippets/[uuid]/page.tsx
import type { Metadata } from 'next';

import { cookies } from 'next/headers';
import request from '@/lib/request';
import dayjs from 'dayjs';
import { ArrowUpRightFromSquare } from 'lucide-react';
import { bundledLanguages, getHighlighter } from 'shiki';
import type { Snippet } from '@/types';
import { DashboardHeader } from '@/components/DashboardHeader';
import relativeTime from 'dayjs/plugin/relativeTime';
import { DeleteSnippetDialog } from '@/components/dialogs/DeleteSnippetDialog';

dayjs.extend(relativeTime);

export const metadata: Metadata = {
	title: 'Dashboard - Snippets - Snippet'
};

const highlighter = await getHighlighter({
	themes: ['github-dark-dimmed'],
	langs: Object.keys(bundledLanguages)
});

export default async function PublicSnippetPage({ params }: { readonly params: { uuid: string } }) {
	const cookiesStore = cookies();
	const token = cookiesStore.get('token')?.value;

	const response = await request.get(
		`snippet/${params.uuid}`,
		{},
		{
			authorization: `Bearer ${token}`
		},
		{
			next: {
				tags: ['snippets']
			}
		}
	);

	const snippet = response.snippet as Snippet;

	return (
		<>
			<DashboardHeader title={snippet.name} subtitle={dayjs(snippet.createdAt).fromNow()}>
				<DeleteSnippetDialog uuid={snippet.uuid} />
			</DashboardHeader>
			<div className="px-2 flex h-full flex-grow flex-col">
				<div className="border border-1 border-accent rounded p-4">
					<div className="flex items-center mb-4">
						<div className="mb-2">
							<h3 className="text-sm leading-tight tracking-tighter">{snippet.language}</h3>
						</div>
						<div className="flex-1" />
						<div className="mb-2">
							<a
								href={snippet.link}
								target="_blank"
								rel="noopener noreferrer"
								className="link inline-flex items-center ml-2"
							>
								Public link <ArrowUpRightFromSquare className="w-3 h-3 ml-1" />
							</a>
							<a
								href={snippet.raw}
								target="_blank"
								rel="noopener noreferrer"
								className="link ml-4 inline-flex items-center"
							>
								Open raw <ArrowUpRightFromSquare className="w-3 h-3 ml-1" />
							</a>
						</div>
					</div>
					<div
						key={snippet.uuid}
						// eslint-disable-next-line react/no-danger
						dangerouslySetInnerHTML={{
							__html: highlighter.codeToHtml(snippet.content, {
								lang: snippet.language,
								theme: 'github-dark-dimmed'
							})
						}}
					/>
				</div>
			</div>
		</>
	);
}
