// packages/next/src/components/ui/switch.tsx
/* eslint-disable react/prop-types */
import * as React from 'react';
import * as SwitchPrimitives from '@radix-ui/react-switch';

import { cn } from '@/lib/utils';

const Switch = React.forwardRef<
	React.ElementRef<typeof SwitchPrimitives.Root>,
	React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root>
>(({ className, ...props }, ref) => (
	<SwitchPrimitives.Root
		className={cn(
			'peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input',
			className
		)}
		{...props}
		ref={ref}
	>
		<SwitchPrimitives.Thumb
			className={cn(
				'pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-0'
			)}
		/>
	</SwitchPrimitives.Root>
));
Switch.displayName = SwitchPrimitives.Root.displayName;

export { Switch };

// packages/nuxt/src/components/ui/switch/Switch.vue
<template>
	<div
		class="flex gap-2 items-center"
		:class="[inverted ? 'flex-row-reverse justify-end' : 'flex-row justify-start']"
	>
		<label
			v-if="$slots.default"
			class="text-theme-1000 dark:text-theme-100 text-[15px] leading-none select-none"
			:for="id"
		>
			<slot />
		</label>
		<SwitchRoot
			:id="id"
			v-model:checked="switchState"
			class="w-[42px] h-[25px] flex bg-black/50 dark:bg-theme-400 shadow-sm rounded-full relative data-[state=checked]:bg-blue-500 dark:data-[state=checked]:bg-blue-500 cursor-pointer focus:shadow-none focus-visible:ring focus-visible:ring-blue-500 focus-visible:ring-offset-1 outline-none"
			@update:checked="onChange"
		>
			<SwitchThumb
				class="block w-[21px] h-[21px] my-auto bg-white shadow-sm rounded-full transition-transform duration-100 translate-x-0.5 will-change-transform data-[state=checked]:translate-x-[19px]"
			/>
		</SwitchRoot>
	</div>
</template>

<script setup lang="ts">
import { SwitchRoot, SwitchThumb } from 'radix-vue';
import { ref } from 'vue';

interface Props {
	disabled?: boolean;
	inverted?: boolean;
}

defineProps<Props>();

const emit = defineEmits(['change']);

const switchState = ref(false);
const id = ref(`switch-${String(Math.random()).slice(2)}`);

const onChange = () => {
	emit('change', switchState.value);
};
</script>
