// packages/frontend/src/pages/dashboard/snippets/index.vue
<template>
	<ScrollArea class="w-full">
		<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
			<Breadcrumbs
				:pages="[
					{
						name: 'Snippets',
						href: '/dashboard/snippets'
					}
				]"
			/>
			<h1 class="text-2xl mt-8 font-semibold text-light-100">Snippets</h1>
			<div class="my-4 h-automobile:py-2 flex mobile:flex-wrap flex-col">
				<div v-for="snippet in snippets" :key="snippet.uuid" class="w-full flex-1 mb-4">
					<div class="flex items-center">
						<div class="mb-2">
							<p class="text-light-100">Name: {{ snippet.name }}</p>
							<p class="text-light-100">Created: {{ dayjs(snippet.createdAt).fromNow() }}</p>
						</div>
						<div class="flex-1"></div>
						<div class="mb-2">
							<a
								:href="snippet.link"
								target="_blank"
								rel="noopener noreferrer"
								class="text-blue-400 hover:text-blue-500 transition-colors duration-200"
							>
								Open snippet
							</a>
							<a
								:href="snippet.raw"
								target="_blank"
								rel="noopener noreferrer"
								class="text-blue-400 hover:text-blue-500 transition-colors duration-200 ml-4"
							>
								Open raw
							</a>
						</div>
					</div>
					<router-link
						:to="`/dashboard/snippets/${snippet.uuid}`"
						class="relative after:hidden hover:after:flex after:content-['View'] after:absolute after:w-full after:h-full after:top-0 after:left-0 after:bg-dark-110 after:opacity-80 after:text-white after:text-4xl after:text-center after:items-center after:justify-center"
					>
						<span
							class="bg-black/30 absolute top-0 right-0 uppercase font-bold text-xs rounded-bl-md px-2 py-1 text-light-100"
						>
							{{ snippet.language }}
						</span>
						<Highlight :language="snippet.language" :code="snippet.content" />
					</router-link>
				</div>
			</div>
		</div>
	</ScrollArea>
</template>

<script setup lang="ts">
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import { onMounted, ref } from 'vue';
import { ScrollArea } from '@/components/ui/scroll-area';
import Breadcrumbs from '~/components/breadcrumbs/Breadcrumbs.vue';
import Highlight from '~/components/highlight/Highlight.vue';
import type { Snippet } from '~/types';
import { getSnippets } from '~/use/api';
dayjs.extend(relativeTime);

const snippets = ref<Snippet[]>([]);

onMounted(async () => {
	const response = await getSnippets();
	snippets.value = response.map((snippet: Snippet) => ({
		...snippet,
		// Grab only the first 10 lines of the snippet
		content: snippet.content.split('\n').slice(0, 10).join('\n')
	}));
});
</script>

// packages/next/src/app/dashboard/snippets/page.tsx
import type { Metadata } from 'next';
import { ArrowUpRightFromSquare, Plus } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { DashboardHeader } from '@/components/DashboardHeader';
import { bundledLanguages, getHighlighter } from 'shiki';
import { cookies } from 'next/headers';
import request from '@/lib/request';
import type { Snippet } from '@/types';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(relativeTime);

export const metadata: Metadata = {
	title: 'Dashboard - Snippets'
};

const highlighter = await getHighlighter({
	themes: ['github-dark-dimmed'],
	langs: Object.keys(bundledLanguages)
});

export default async function DashboardPage() {
	const cookiesStore = cookies();
	const token = cookiesStore.get('token')?.value;

	const response = await request.get(
		`snippets`,
		{},
		{
			authorization: `Bearer ${token}`
		},
		{
			next: {
				tags: ['snippets']
			}
		}
	);

	return (
		<>
			<DashboardHeader title="Snippets" subtitle="Manage and create snippets">
				<Button>
					<Plus className="mr-2 h-4 w-4" />
					New snippet
				</Button>
			</DashboardHeader>
			<div className="px-2 flex flex-col gap-6">
				{response.snippets.map((snippet: Snippet) => {
					return (
						<div className="border border-1 border-accent rounded p-4">
							<div className="flex items-center mb-4">
								<div className="mb-2">
									<h2 className="text-xl font-extrabold leading-tight tracking-tighter md:text-2x">
										<a href={`/dashboard/snippets/${snippet.uuid}`} className="link">
											{snippet.name}
										</a>
									</h2>
									<h3 className="text-sm leading-tight tracking-tighter">
										{dayjs(snippet.createdAt).fromNow()}
									</h3>
								</div>
								<div className="flex-1" />
								<div className="mb-2">
									<a
										href={snippet.link}
										target="_blank"
										rel="noopener noreferrer"
										className="link inline-flex items-center ml-2"
									>
										Public link <ArrowUpRightFromSquare className="w-3 h-3 ml-1" />
									</a>
									<a
										href={snippet.raw}
										target="_blank"
										rel="noopener noreferrer"
										className="link ml-4 inline-flex items-center"
									>
										Open raw <ArrowUpRightFromSquare className="w-3 h-3 ml-1" />
									</a>
								</div>
							</div>
							<div
								key={snippet.uuid}
								// eslint-disable-next-line react/no-danger
								dangerouslySetInnerHTML={{
									__html: highlighter.codeToHtml(
										snippet.content.split('\n').slice(0, 10).join('\n'),
										{
											lang: snippet.language,
											theme: 'github-dark-dimmed'
										}
									)
								}}
							/>
						</div>
					);
				})}
			</div>
		</>
	);
}
