// packages/nuxt/src/components/ui/accordion/Accordion.vue
<template>
	<Accordion class="w-full" :value="selectedValue" @change="onChange">
		<AccordionItem
			v-for="(item, index) in items"
			:key="item.key ? item.key : `accordion-${index}`"
			:value="item.key ? item.key : item.title"
		>
			<AccordionTrigger
				class="p-4 items-center cursor-pointer flex font-bold justify-between w-full"
				:class="index !== 0 ? 'border-t-[1px] border-theme-600 dark:border-theme-300' : ''"
			>
				<h1>{{ item.title }}</h1>
				<ChevronDownIcon
					class="h-6 w-6 transition-transform duration-200"
					:class="(item.key ? item.key : item.title) === selectedValue ? 'rotate-180' : 'rotate-0'"
				/>
			</AccordionTrigger>
			<AccordionContent
				class="pl-4 pb-6 pr-8 animate-in fade-in duration-200"
				:class="(item.key ? item.key : item.title) === selectedValue ? 'flex' : 'hidden'"
				><p>{{ item.content }}</p></AccordionContent
			>
		</AccordionItem>
	</Accordion>
</template>

<script setup lang="ts">
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@ark-ui/vue';
import { ChevronDownIcon } from 'lucide-vue-next';
import { ref, onMounted } from 'vue';

interface Props {
	items: [
		{
			title: string;
			content: string;
			key?: string;
		}
	];
}
const props = defineProps<Props>();
const emit = defineEmits(['change']);

const selectedValue = ref();

onMounted(() => {
	selectedValue.value = props.items[0].key ? props.items[0].key : props.items[0].title;
});

const onChange = (value: string[]) => {
	selectedValue.value = value[0];
	emit('change', value[0]);
};
</script>

// packages/next/src/components/ui/accordion.tsx
/* eslint-disable react/prop-types */
import * as React from 'react';
import * as AccordionPrimitive from '@radix-ui/react-accordion';
import { ChevronDown } from 'lucide-react';

import { cn } from '@/lib/utils';

const Accordion = AccordionPrimitive.Root;

const AccordionItem = React.forwardRef<
	React.ElementRef<typeof AccordionPrimitive.Item>,
	React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Item>
>(({ className, ...props }, ref) => (
	<AccordionPrimitive.Item ref={ref} className={cn('border-b', className)} {...props} />
));
AccordionItem.displayName = 'AccordionItem';

const AccordionTrigger = React.forwardRef<
	React.ElementRef<typeof AccordionPrimitive.Trigger>,
	React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Trigger>
>(({ className, children, ...props }, ref) => (
	<AccordionPrimitive.Header className="flex">
		<AccordionPrimitive.Trigger
			ref={ref}
			className={cn(
				'flex flex-1 items-center justify-between py-4 font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180',
				className
			)}
			{...props}
		>
			{children}
			<ChevronDown className="h-4 w-4 shrink-0 transition-transform duration-200" />
		</AccordionPrimitive.Trigger>
	</AccordionPrimitive.Header>
));
AccordionTrigger.displayName = AccordionPrimitive.Trigger.displayName;

const AccordionContent = React.forwardRef<
	React.ElementRef<typeof AccordionPrimitive.Content>,
	React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Content>
>(({ className, children, ...props }, ref) => (
	<AccordionPrimitive.Content
		ref={ref}
		className="overflow-hidden text-sm transition-all data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
		{...props}
	>
		<div className={cn('pb-4 pt-0', className)}>{children}</div>
	</AccordionPrimitive.Content>
));

AccordionContent.displayName = AccordionPrimitive.Content.displayName;

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent };
