// packages/nuxt/src/components/ui/button/Button.vue
<template>
	<button
		type="button"
		:class="button({ color: variant, disabled: disabled || loading, className })"
		@click="$emit('click')"
	>
		<template v-if="loading">
			<Loader2Icon class="animate-spin mr-2 absolute" />
		</template>
		<span class="flex text-inherit" :class="[loading ? 'opacity-0' : 'opacity-100']">
			<slot />
		</span>
	</button>
</template>

<script setup lang="ts">
import { Loader2Icon } from 'lucide-vue-next';
import { tv } from 'tailwind-variants';

interface Props {
	variant?: 'primary' | 'success' | 'destructive' | 'none';
	loading?: boolean;
	disabled?: boolean;
	className?: string;
}

withDefaults(defineProps<Props>(), {
	variant: 'primary',
	className: ''
});

defineEmits(['click']);

const button = tv({
	base: [
		'text-theme-1000 dark:text-theme-100 border font-medium inline-flex justify-center items-center leading-6 px-4 py-2 rounded-md shadow-sm text-base w-fit whitespace-no-wrap relative',
		'focus:shadow-none focus-visible:ring focus-visible:ring-blue-500 focus-visible:ring-offset-1 outline-none'
	],
	variants: {
		color: {
			primary: [
				'bg-white hover:bg-gray-50 border-gray-200',
				'dark:bg-theme-500 hover:dark:bg-theme-600 dark:border-theme-400'
			],
			success:
				'bg-green-600 hover:bg-green-700 text-theme-100 dark:bg-green-700 dark:hover:bg-green-800 dark:border-green-700',
			destructive: 'bg-red-500 hover:bg-red-600 text-theme-100 border-red-700 dark:border-red-500',
			none: 'bg-transparent border-transparent p-0'
		},
		disabled: {
			true: 'opacity-70 pointer-events-none'
		}
	},
	defaultVariants: {
		color: 'primary'
	}
});
</script>

// packages/next/src/components/ui/button.tsx
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';

import { cn } from '@/lib/utils';

const buttonVariants = cva(
	'inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none ring-offset-background',
	{
		variants: {
			variant: {
				default: 'bg-primary text-primary-foreground hover:bg-primary/90',
				destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
				outline: 'border border-input hover:bg-accent hover:text-accent-foreground',
				secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
				ghost: 'hover:bg-accent hover:text-accent-foreground',
				link: 'underline-offset-4 hover:underline text-primary'
			},
			size: {
				default: 'h-10 py-2 px-4',
				sm: 'h-9 px-3 rounded-md',
				lg: 'h-11 px-8 rounded-md',
				icon: 'h-10 w-10'
			}
		},
		defaultVariants: {
			variant: 'default',
			size: 'default'
		}
	}
);

export interface ButtonProps
	extends React.ButtonHTMLAttributes<HTMLButtonElement>,
		VariantProps<typeof buttonVariants> {
	readonly asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
	({ className, variant, size, asChild = false, ...props }, ref) => {
		const Comp = asChild ? Slot : 'button';
		return <Comp className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />;
	}
);
Button.displayName = 'Button';

export { Button, buttonVariants };
