// packages/frontend/src/components/ui/separator/Separator.vue
<script setup lang="ts">
import { Separator, type SeparatorProps } from 'radix-vue';
import { cn } from '@/lib/utils';

const props = defineProps<SeparatorProps & { class?: string }>();
</script>

<template>
	<Separator
		:class="[
			cn('shrink-0 bg-secondary', props.class),
			props.orientation === 'vertical' ? 'w-px h-full' : 'h-px w-full'
		]"
	/>
</template>

// packages/next/src/components/ui/separator.tsx
/* eslint-disable react/prop-types */
import * as React from 'react';
import * as SeparatorPrimitive from '@radix-ui/react-separator';

import { cn } from '@/lib/utils';

const Separator = React.forwardRef<
	React.ElementRef<typeof SeparatorPrimitive.Root>,
	React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root>
>(({ className, orientation = 'horizontal', decorative = true, ...props }, ref) => (
	<SeparatorPrimitive.Root
		ref={ref}
		decorative={decorative}
		orientation={orientation}
		className={cn(
			'shrink-0 bg-border',
			orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]',
			className
		)}
		{...props}
	/>
));
Separator.displayName = SeparatorPrimitive.Root.displayName;

export { Separator };
